export const series = [
  'Mario Bros.',
  'Legend of Zelda',
  'Pokémon',
  'Warcraft',
  'The Elder Scrolls',
  'Fallout',
  'Doom',
  'Kingdom Hearts',
  'Crash Bandicoot',
  'Donkey Kong',
  'Tekken',
  'Borderlands',
  'The Sims',
  'Dead Space',
  'Animal Crossing',
  'Fable',
  'Contra',
  'Team Fortress',
  'Punch-Out',
  'Saints Row',
  'Jak and Daxter',
  'Guilty Gear',
  'Starcraft',
  'Nier',
  'Warhammer',
  'Final Fantasy',
  'Pikmin',
  'Tales series (Tales of x)',
  'Mana Series (x of Mana)',
  'Metal Gear',
  'God of War',
  'Tetris',
  'Red Dead Redemption',
  'Street Fighter',
  'Chrono series',
  'Rachet and Clank',
  'Call of Duty',
  'Age of Empires',
  'Need for Speed',
  'Harvest Moon',
  'Prince of Persia',
  'Max Payne',
  'Ninja Gaiden',
  'Persona',
  'Bayonetta',
  'Medal of Honor',
  'Dead or Alive',
  'Deus Ex',
  'Drakengard',
  'Breath of Fire',
  'Dragon Quest',
  'Halo',
  'Grand Theft Auto',
  'Diablo',
  "Assassin's Creed",
  'Metroid',
  'Bioshock',
  'Mass Effect',
  'Star Fox',
  'Last of Us',
  'Fire Emblem',
  'Far Cry',
  'Resident Evil',
  "Tony Hawk's Pro Skater",
  'Gran Tourismo',
  'Rayman',
  'Castlevania',
  'Soul Calibur',
  'Shin Megami Tensai',
  'Yakuza',
  'Command & Conquer',
  'SaGa',
  'Total War',
  'Phantasy Star',
  'Parasite Eve',
  'Mortal Kombat',
  'Mega Man',
  'Uncharted',
  'Tomb Raider',
  'Portal',
  'Sonic the Hedgehog',
  'The Witcher',
  'Half-Life',
  'Spyro the Dragon',
  'Dark Souls',
  'Devil May Cry',
  'Silent Hill',
  'Hitman',
  'Dragon Age',
  'Gears of War',
  'Banjo-Kazooie',
  'Counter-Strike',
  'Worms',
  'Shadow Hearts',
  'Bomberman',
  'Monster Hunter',
  'Shenmue',
  'Watch Dogs',
  'Dishonored',
  'Wild Arms',
]
